#!/bin/python3
# todo send link to website to ceskevylety@seznam.cz
# todo https://www.nasiptaci.info/zvuky-ptaku/
import shutil
from typing import Dict
from pathlib import Path
from urllib import parse
from urllib.error import HTTPError
from PIL import Image

import os
import urllib
import requests
import json
import wget
import time
import yaml

# Taken from the birdphoto website html code.
birdphoto_id_map: Dict[int, str] = {'Alexandr velký': 637,
                                    'Alka malá': 669,
                                    'Alkoun malý': 630,
                                    'Alkoun obecný': 674,
                                    'Alkoun tlustozobý': 671,
                                    'Alexandr malý': 631,
                                    'Alkoun úzkozobý': 670,
                                    'Bažant kolchický tmavý': 610,
                                    'Bažant královský': 277,
                                    'Bažant obecný': 35,
                                    'Bekasina otavní': 53,
                                    'Bekasina větší': 627,
                                    'Bělokur horský': 623,
                                    'Bělokur rousný': 672,
                                    'Bělořit arabský': 724,
                                    'Bělořit okrový': 423,
                                    'Bělořit perský': 701,
                                    'Bělořit plavý': 645,
                                    'Bělořit pouštní': 711,
                                    'Bělořit skalní': 646,
                                    'Bělořit šedý': 89,
                                    'Berneška bělolící': 566,
                                    'Berneška tmavá': 639,
                                    'Berneška velká': 231,
                                    'Bramborníček černohlavý': 37,
                                    'Bramborníček hnědý': 31,
                                    'Brhlík dlouhozobý': 649,
                                    'Brhlík lesní': 264,
                                    'Brhlík skalní': 498,
                                    'Brkoslav severní': 90,
                                    'Břehouš černoocasý': 47,
                                    'Břehouš rudý': 624,
                                    'Břehule říční': 128,
                                    'Budníček kanárský': 316,
                                    'Budníček kavkazský': 656,
                                    'Budníček lesní': 322,
                                    'Budníček malinký': 716,
                                    'Budníček menší': 143,
                                    'Budníček menší sibiřský': 725,
                                    'Budníček severní': 665,
                                    'Budníček větší': 134,
                                    'Budníček zlatohlavý': 629,
                                    'Budníček žlutavý': 657,
                                    'Bukač velký': 55,
                                    'Bukáček malý': 364,
                                    'Bulbul arabský': 707,
                                    'Bulbul šupinkový': 720,
                                    'Buřňák šedý': 527,
                                    'Cetie jižní ': 518,
                                    'Cvrčilka říční': 220,
                                    'Cvrčilka slavíková': 115,
                                    'Cvrčilka zelená': 129,
                                    'Čáp bílý': 13,
                                    'Čáp černý': 116,
                                    'Čáp simbil': 685,
                                    'Čečetka bělavá': 625,
                                    'Čečetka tmavá': 339,
                                    'Čečetka zimní': 378,
                                    'Čejka černoprsá': 703,
                                    'Čejka chocholatá': 58,
                                    'Čejka trnitá': 549,
                                    'Červenka obecná': 206,
                                    'Čírka karolínská': 528,
                                    'Čírka modrá': 138,
                                    'Čírka obecná': 176,
                                    'Čírka úzkozobá': 477,
                                    'Čížek lesní': 91,
                                    'Datel černý': 144,
                                    'Datlík tříprstý': 417,
                                    'Dlask tlustozobý': 83,
                                    'Drop velký': 270,
                                    'Drozd brávník': 386,
                                    'Drozd cvrčala': 433,
                                    'Drozd kvíčala': 57,
                                    'Drozd rudonohý': 185,
                                    'Drozd zpěvný': 218,
                                    'Drozdec mnohohlasý': 186,
                                    'Dřemlík tundrový': 24,
                                    'Dudek chocholatý': 36,
                                    'Dytík skvrnitý': 682,
                                    'Dytík úhorní': 519,
                                    'Frankolin křepelčí': 712,
                                    'Frankolín obecný': 546,
                                    'Havran polní': 126,
                                    'Hohol bělavý ': 638,
                                    'Hohol severní': 95,
                                    'Hoholka lední': 223,
                                    'Holub doupňák': 64,
                                    'Holub hřivnáč': 12,
                                    'Holub sahelský': 683,
                                    'Holub skalní': 473,
                                    'Holub věžák': 385,
                                    'Hrdlička divoká': 97,
                                    'Hrdlička chechtavá': 730,
                                    'Hrdlička kapská': 718,
                                    'Hrdlička senegalská': 425,
                                    'Hrdlička východní': 608,
                                    'Hrdlička zahradní': 69,
                                    'Husa běločelá': 170,
                                    'Husa krátkozobá': 635,
                                    'Husa malá': 636,
                                    'Husa polní': 159,
                                    'Husa sněžní': 792,
                                    'Husa tibetská / Husa indická': 634,
                                    'Husa velká': 130,
                                    'Husice liščí': 232,
                                    'Husice nilská': 434,
                                    'Husice rezavá': 494,
                                    'Hvízdák euroasijský': 430,
                                    'Hvízdák chilský / Hvízdák stejnobarvý': 692,
                                    'Hýl křivčí': 666,
                                    'Hýl obecný': 87,
                                    'Hýl pustinný': 647,
                                    'Hýl rudý': 145,
                                    'Hýl velký': 658,
                                    'Chaluha malá': 626,
                                    'Chaluha pomořanská': 483,
                                    'Chaluha příživná': 363,
                                    'Chocholouš obecný': 82,
                                    'Chřástal kropenatý': 620,
                                    'Chřástal malý': 438,
                                    'Chřástal polní': 135,
                                    'Chřástal vodní': 266,
                                    'Ibis hnědý': 559,
                                    'Ibis posvátný': 475,
                                    'Iranie bělohrdlá': 653,
                                    'Jeřáb popelavý': 157,
                                    'Jeřábek lesní': 407,
                                    'Jespáček ploskozobý': 480,
                                    'Jespák bojovný': 6,
                                    'Jespák křivozobý': 443,
                                    'Jespák malý ': 439,
                                    'Jespák mořský': 567,
                                    'Jespák obecný': 172,
                                    'Jespák písečný': 444,
                                    'Jespák rezavý': 661,
                                    'Jespák šedý': 399,
                                    'Jestřáb lesní': 16,
                                    'Jiřička obecná': 109,
                                    'Kačka strakatá': 621,
                                    'Kachna divoká': 46,
                                    'Kachnice bělohlavá': 734,
                                    'Kachnice kaštanová': 815,
                                    'Kachnička karolínská': 245,
                                    'Kachnička mandarinská': 429,
                                    'Kajka mořská': 230,
                                    'Kalandra dvouskvrnná': 651,
                                    'Kalandra zpěvná': 464,
                                    'Kalous pustovka': 33,
                                    'Kalous ušatý': 50,
                                    'Kalypta menší': 207,
                                    'Kamenáček pestrý': 359,
                                    'Kanár divoký': 321,
                                    'Káně bělochvostá': 448,
                                    'Káně lesní': 4,
                                    'Káně lesní ruská': 660,
                                    'Káně rousná': 98,
                                    'Kavče červenozobé': 644,
                                    'Kavče žlutozobé': 419,
                                    'Kavka obecná': 125,
                                    'Keptuška běloocasá': 551,
                                    'Ketupa rybí': 558,
                                    'Koliha malá': 370,
                                    'Koliha velká': 158,
                                    'Kolpík bílý': 94,
                                    'Kondor krocanovitý': 188,
                                    'Konipas bílý': 67,
                                    'Konipas bílý amurský': 717,
                                    'Konipas citrónový': 436,
                                    'Konipas horský': 239,
                                    'Konipas luční': 8,
                                    'Konopka obecná': 101,
                                    'Konopka žlutozobá': 259,
                                    'Kopřivka obecná': 137,
                                    'Kormorán běloprsý': 727,
                                    'Kormorán chocholatý': 160,
                                    'Kormorán malý': 164,
                                    'Kormorán velký': 59,
                                    'Koroptev polní': 28,
                                    'Koroptev pouštní': 695,
                                    'Kos černý': 74,
                                    'Kos horský': 251,
                                    'Krahujec krátkoprstý': 504,
                                    'Krahujec obecný': 105,
                                    'Králíček obecný': 312,
                                    'Králíček ohnivý': 240,
                                    'Krkavec krátkoocasý': 721,
                                    'Krkavec velký': 140,
                                    'Kruhoočko etiopské': 697,
                                    'Krutihlav obecný': 260,
                                    'Křepelka polní': 133,
                                    'Křivka obecná': 283,
                                    'Křivka velká': 632,
                                    'Kukačka ani': 183,
                                    'Kukačka koel': 688,
                                    'Kukačka Merlinova': 187,
                                    'Kukačka obecná': 112,
                                    'Kulík bledý': 243,
                                    'Kulík hnědý': 388,
                                    'Kulík menší': 680,
                                    'Kulík mořský': 177,
                                    'Kulík písečný': 174,
                                    'Kulík říční': 20,
                                    'Kulík tlustozobý': 198,
                                    'Kulík větší': 709,
                                    'Kulík zlatý': 178,
                                    'Kulík zrzoocasý': 210,
                                    'Kulíšek kubánský': 197,
                                    'Kulíšek nejmenší': 421,
                                    'Kurlan chřástalovitý': 182,
                                    'Kvakoš noční': 23,
                                    'Labuť černá': 209,
                                    'Labuť malá': 522,
                                    'Labuť velká': 29,
                                    'Labuť zpěvná': 127,
                                    'Ledňáček říční': 39,
                                    'Lejsek bělokrký': 317,
                                    'Lejsek černohlavý': 398,
                                    'Lejsek malý ': 418,
                                    'Lejsek šedý': 238,
                                    'Lejskovec nádherný': 698,
                                    'Lelek lesní': 408,
                                    'Linduška dlouhozobá': 719,
                                    'Linduška horská': 258,
                                    'Linduška kanárská': 530,
                                    'Linduška lesní': 457,
                                    'Linduška luční': 248,
                                    'Linduška rudokrká': 351,
                                    'Linduška skalní': 492,
                                    'Linduška úhorní ': 442,
                                    'Luňák červený': 257,
                                    'Luňák hnědý': 131,
                                    'Lyska černá': 77,
                                    'Lyska hřebenatá': 478,
                                    'Lyskonoh ploskozobý': 662,
                                    'Lyskonoh úzkozobý': 357,
                                    'Lžičák pestrý': 118,
                                    'Majna obecná': 891,
                                    'Mandelík hajní': 162,
                                    'Mandelík indický': 679,
                                    'Mlynařík dlouhoocasý': 308,
                                    'Modruška tajgová': 667,
                                    'Morčák bílý': 151,
                                    'Morčák prostřední': 488,
                                    'Morčák velký': 96,
                                    'Moták lužní': 30,
                                    'Moták pilich': 122,
                                    'Moták pochop': 41,
                                    'Moták stepní': 731,
                                    'Moudivláček lužní': 299,
                                    'Orebice berberská': 311,
                                    'Orebice černohlavá': 732,
                                    'Orebice čukar': 654,
                                    'Orebice horská': 502,
                                    'Orebice rudá': 529,
                                    'Orel jestřábí': 562,
                                    'Orel královský': 78,
                                    'Orel křiklavý': 111,
                                    'Orel mořský': 75,
                                    'Orel nejmenší': 571,
                                    'Orel skalní': 110,
                                    'Orel stepní': 234,
                                    'Orel volavý': 596,
                                    'Orlík krátkoprstý': 2,
                                    'Orlosup bradatý': 547,
                                    'Orlovec říční': 25,
                                    'Ořešník kropenatý': 600,
                                    'Ostralka štíhlá': 119,
                                    'Ostříž jižní': 469,
                                    'Ostříž lesní': 34,
                                    'Ouhorlík stepní': 468,
                                    'Papoušek mniší / Mníšek šedý': 691,
                                    'Papuchalk severní': 622,
                                    'Pelikán bílý': 466,
                                    'Pelikán kadeřavý': 465,
                                    'Pěnice bělohrdlá': 516,
                                    'Pěnice černohlavá': 262,
                                    'Pěnice černolící': 652,
                                    'Pěnice dlouhozobá': 501,
                                    'Pěnice hnědokřídlá': 326,
                                    'Pěnice pokřovní': 336,
                                    'Pěnice vlašská': 330,
                                    'Pěnice vousatá': 500,
                                    'Pěnkava jikavec': 56,
                                    'Pěnkava kanárská': 313,
                                    'Pěnkava obecná': 148,
                                    'Pěnkavák sněžný': 422,
                                    'Pěvec ryšavý': 550,
                                    'Pěvuška modrá': 397,
                                    'Pěvuška podhorní': 403,
                                    'Pěvuška skalní': 643,
                                    'Pisík obecný': 124,
                                    'Pisila čáponohá': 400,
                                    'Plameňák růžový': 520,
                                    'Polák chocholačka': 19,
                                    'Polák kaholka': 487,
                                    'Polák malý': 404,
                                    'Polák proužkozobý': 633,
                                    'Polák velký': 121,
                                    'Poštolka jižní': 460,
                                    'Poštolka obecná': 7,
                                    'Poštolka pestrá': 199,
                                    'Poštolka rudonohá': 9,
                                    'Potápka černokrká': 224,
                                    'Potápka malá': 72,
                                    'Potápka roháč': 63,
                                    'Potápka rudokrká': 409,
                                    'Potápka žlutorohá': 490,
                                    'Potáplice lední': 538,
                                    'Potáplice malá': 373,
                                    'Potáplice severní': 387,
                                    'Potáplice žlutozobá': 536,
                                    'Prinie obecná': 726,
                                    'Puštík bělavý': 441,
                                    'Puštík obecný': 150,
                                    'Puštík vousatý': 663,
                                    'Racek arabský': 690,
                                    'Racek arménský': 642,
                                    'Racek bělohlavý': 152,
                                    'Racek bouřní': 149,
                                    'Racek černohlavý': 573,
                                    'Racek chechtavý': 139,
                                    'Racek malý': 73,
                                    'Racek mořský': 391,
                                    'Racek polární': 513,
                                    'Racek Sabinův': 598,
                                    'Racek středomořský': 252,
                                    'Racek stříbřitý': 244,
                                    'Racek šedý': 489,
                                    'Racek tenkozobý': 553,
                                    'Racek tříprstý': 372,
                                    'Racek zelenonohý': 476,
                                    'Racek žlutonohý': 431,
                                    'Racek žlutonohý západosibiřský': 678,
                                    'Rákosník hlučnohlasý': 728,
                                    'Rákosník obecný': 588,
                                    'Rákosník ostřicový': 537,
                                    'Rákosník plavý ': 650,
                                    'Rákosník pokřovní': 664,
                                    'Rákosník proužkovaný': 49,
                                    'Rákosník tamaryškový': 831,
                                    'Rákosník velký': 107,
                                    'Rákosník zpěvný': 132,
                                    'Raroh jižní': 556,
                                    'Raroh lovecký': 432,
                                    'Raroh velký': 27,
                                    'Rehek bělokřídlý': 659,
                                    'Rehek domácí': 103,
                                    'Rehek zahradní': 338,
                                    'Rorýs obecný': 327,
                                    'Rorýs šedohnědý': 194,
                                    'Rorýs velký': 362,
                                    'Rybák arabský': 723,
                                    'Rybák bahenní': 11,
                                    'Rybák bělokřídlý': 61,
                                    'Rybák černozobý': 554,
                                    'Rybák černý': 32,
                                    'Rybák dlouhoocasý': 355,
                                    'Rybák chocholatý': 677,
                                    'Rybák malý': 114,
                                    'Rybák obecný': 113,
                                    'Rybák oranžovozobý': 694,
                                    'Rybák severní ': 427,
                                    'Rybák velkozobý': 561,
                                    'Sedmihlásek hajní': 323,
                                    'Sedmihlásek šedý': 557,
                                    'Skalníček černoocasý': 736,
                                    'Skalník modrý': 471,
                                    'Skalník zpěvný': 472,
                                    'Skorec vodní': 17,
                                    'Skřivan dudkovitý': 708,
                                    'Skřivan lesní': 309,
                                    'Skřivan ouškatý': 389,
                                    'Skřivan polní': 18,
                                    'Skřivan pouštní': 696,
                                    'Skřivan zpěvný': 722,
                                    'Skřivánek krátkoprstý': 463,
                                    'Skřivánek menší': 552,
                                    'Slavík modráček středoevropský': 163,
                                    'Slavík modráček tundrový': 271,
                                    'Slavík obecný': 120,
                                    'Slavík tmavý': 533,
                                    'Slípka modrá': 491,
                                    'Slípka zelenonohá': 175,
                                    'Slučka malá ': 426,
                                    'Sluka lesní': 93,
                                    'Sněhule severní': 535,
                                    'Snovač žluví': 686,
                                    'Sojka obecná': 92,
                                    'Sokol stěhovavý': 45,
                                    'Sokol stěhovavý tundrový': 641,
                                    'Sokol šahin': 710,
                                    'Sovice krahujová': 563,
                                    'Stehlík obecný': 48,
                                    'Stehlíkovec dlaskovitý': 684,
                                    'Straka obecná': 104,
                                    'Strakapoud bělohřbetý': 540,
                                    'Strakapoud jižní': 331,
                                    'Strakapoud malý': 153,
                                    'Strakapoud prostřední': 369,
                                    'Strakapoud velký': 60,
                                    'Strdimil nachový': 729,
                                    'Strdimil nilský': 713,
                                    'Strdimil palestinský': 714,
                                    'Strdimil zářivý': 693,
                                    'Strnad cvrčivý': 474,
                                    'Strnad černohlavý': 462,
                                    'Strnad luční': 44,
                                    'Strnad malinký': 613,
                                    'Strnad obecný': 76,
                                    'Strnad pustinný': 655,
                                    'Strnad rákosní': 106,
                                    'Strnad rolní': 675,
                                    'Strnad severní': 348,
                                    'Strnad skalní': 687,
                                    'Strnad viničný': 406,
                                    'Strnad zahradní': 62,
                                    'Stříbrozobka malabarská': 740,
                                    'Stříbrozobka zpěvná': 741,
                                    'Střízlík obecný': 136,
                                    'Sup bělohlavý ': 411,
                                    'Sup hnědý': 555,
                                    'Sup mrchožravý': 461,
                                    'Sýc rousný': 54,
                                    'Sýček obecný': 123,
                                    'Sýkora africká': 315,
                                    'Sýkora azurová': 602,
                                    'Sýkora babka': 384,
                                    'Sýkora koňadra': 3,
                                    'Sýkora laponská': 676,
                                    'Sýkora lužní': 451,
                                    'Sýkora modřinka': 52,
                                    'Sýkora parukářka': 14,
                                    'Sýkora temná': 628,
                                    'Sýkora uhelníček': 154,
                                    'Sýkořice vínoprsá': 640,
                                    'Sýkořice vousatá': 10,
                                    'Šoupálek dlouhoprstý': 305,
                                    'Šoupálek krátkoprstý ': 435,
                                    'Špaček obecný': 171,
                                    'Špaček růžový': 548,
                                    'Špaček Tristramův': 699,
                                    'Tangara bahamská': 195,
                                    'Tenkozobec opačný': 301,
                                    'Terej bílý': 750,
                                    'Terej maskový': 715,
                                    'Tetřev hlušec': 65,
                                    'Tetřívek kavkazský': 648,
                                    'Tetřívek obecný': 402,
                                    'Tody kubánský': 200,
                                    'Ťuhýk černohřbetý': 503,
                                    'Ťuhýk menší': 66,
                                    'Ťuhýk obecný': 5,
                                    'Ťuhýk rudohlavý': 278,
                                    'Ťuhýk středoasijský': 733,
                                    'Ťuhýk šedý': 155,
                                    'Turpan černý': 493,
                                    'Turpan hnědý': 392,
                                    'Ústřičník velký': 347,
                                    'Včelojed chocholatý': 702,
                                    'Včelojed lesní': 168,
                                    'Vlaštovka obecná': 146,
                                    'Vlaštovka pohorská / Břehule skalní': 609,
                                    'Vlaštovka skalní': 205,
                                    'Vlha modrolící': 541,
                                    'Vlha pestrá': 38,
                                    'Vlha proměnlivá': 704,
                                    'Vlhovec kubánský': 196,
                                    'Vodouš bahenní': 21,
                                    'Vodouš kropenatý': 367,
                                    'Vodouš rudonohý': 156,
                                    'Vodouš šedý': 165,
                                    'Vodouš štíhlý': 616,
                                    'Vodouš tmavý': 437,
                                    'Volavka bílá': 22,
                                    'Volavka červená': 147,
                                    'Volavka popelavá': 71,
                                    'Volavka proměnlivá': 202,
                                    'Volavka prostřední': 700,
                                    'Volavka rusohlavá': 184,
                                    'Volavka stříbřitá': 88,
                                    'Volavka vlasatá': 102,
                                    'Volavka západní': 681,
                                    'Vrabec domácí': 43,
                                    'Vrabec italský': 287,
                                    'Vrabec pokřovní': 68,
                                    'Vrabec polní': 70,
                                    'Vrabec skalní': 542,
                                    'Vrána domácí': 706,
                                    'Vrána obecná černá': 228,
                                    'Vrána obecná šedá': 219,
                                    'Výr velký': 108,
                                    'Výreček arabský': 689,
                                    'Výreček malý': 532,
                                    'Zedníček skalní': 455,
                                    'Zrzohlávka rudozobá': 40,
                                    'Zvonek zelený': 99,
                                    'Zvonohlík jemenský': 705,
                                    'Zvonohlík královský': 424,
                                    'Zvonohlík zahradní': 100,
                                    'Žluna šedá': 181,
                                    'Žluna zelená': 42,
                                    'Žluva hajní': 117}

avibase_id_map = {'Anser caerulescens': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D3A260BCA65503C6',
                  'Anser anser': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=4AED44E819A43204',
                  'Anser albifrons': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=466E9077BE220EBE',
                  'Anser erythropus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=184D232983E7AD10',
                  'Anser fabalis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BDB497A352D152DB',
                  'Anser serrirostris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=AD849FCBCC68A520',
                  'Anser brachyrhynchus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=AFA7EE7470F000E9',
                  'Branta bernicla': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3E04020B54C14FCC',
                  'Branta leucopsis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3163ED86A508BB83',
                  'Branta hutchinsii': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=60214D4970BA4158',
                  'Branta canadensis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B59E18633E2EFD25',
                  'Branta ruficollis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0D280B3F11B099B2',
                  'Cygnus olor': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=694C127A5D849FFE',
                  'Cygnus columbianus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0BCBA6B9CC19E7BA',
                  'Cygnus cygnus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BDDB5670D2D20A55',
                  'Alopochen aegyptiaca': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=DA2F24E310CF72A6',
                  'Tadorna ferruginea': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1F9D883EB44DEFD6',
                  'Tadorna tadorna': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=5EAB32D3007896F3',
                  'Aix sponsa': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=27B2749A88E3E2C8',
                  'Aix galericulata': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E1714A09EA1DFD1D',
                  'Spatula querquedula': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F577BA0F5BB7BD3F',
                  'Spatula discors': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=90E2543E9A4ABA0A',
                  'Spatula clypeata': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=ED4CE8E7CFF43696',
                  'Mareca strepera': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C235A4D712BB8855',
                  'Mareca penelope': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=15EE0D3685082E13',
                  'Mareca americana': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D201EB7230F20770',
                  'Anas platyrhynchos': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=85625D75F2524457',
                  'Anas acuta': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=56CCA7179C9FA71D',
                  'Anas crecca': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BC6C3CCE5C1B5D9B',
                  'Marmaronetta angustirostris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6362936EA12874F1',
                  'Netta rufina': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3EC2CDA952B4A18C',
                  'Aythya valisineria': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1929E1E16E073570',
                  'Aythya ferina': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A96692E0C9F7508B',
                  'Aythya collaris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0783A7EA9C26947D',
                  'Aythya nyroca': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=7CF91527F5832F30',
                  'Aythya fuligula': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=67CEA1C1FC88F1DB',
                  'Aythya marila': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=25C94A8F90A829F7',
                  'Polysticta stelleri': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BA07D0168474EB92',
                  'Somateria spectabilis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F3D7491432CC59E7',
                  'Somateria mollissima': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B77377EEB852D0AF',
                  'Histrionicus histrionicus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BCBD2EAECA774B19',
                  'Melanitta fusca': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BAF44E36E8D647CB',
                  'Melanitta nigra': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=246981996A4998ED',
                  'Clangula hyemalis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=AF0C7BDEC7CEBAAC',
                  'Bucephala albeola': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FB7383856D0DB2EA',
                  'Bucephala clangula': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=68EA281AF74846D2',
                  'Bucephala islandica': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9456DEDF7E1AADF3',
                  'Mergellus albellus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F1F520368CC95F88',
                  'Lophodytes cucullatus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=60E6081E3DF8CFA4',
                  'Mergus merganser': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=407E2CA886367DBB',
                  'Mergus serrator': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=8DB64266A42FC19B',
                  'Oxyura jamaicensis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=675EEA7FBD490CED',
                  'Oxyura leucocephala': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=2E40EF2C53646E30',
                  'Tetrastes bonasia': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B8CA2EEB4E7E0CA3',
                  'Tetrao urogallus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C3221EE24B948F50',
                  'Lyrurus tetrix': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D4441CD6E9C993EF',
                  'Perdix perdix': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C013A20E7F91419D',
                  'Syrmaticus reevesii': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=94785AFFA715F16E',
                  'Phasianus colchicus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=2FA39DCD42F80BC9',
                  'Coturnix coturnix': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=CAFE345DCABD8BF8',
                  'Phoenicopterus roseus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0F9B5174A8ACF737',
                  'Tachybaptus ruficollis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=215FEA89A0F19F5C',
                  'Podiceps auritus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=018B316959E84738',
                  'Podiceps grisegena': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1CBD2CED48B674A4',
                  'Podiceps cristatus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=8F269702DC208010',
                  'Podiceps nigricollis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=32DCEC14D7AE129B',
                  'Columba livia': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BBA263C235B15B88',
                  'Columba oenas': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=68E4C0D1404A46D8',
                  'Columba palumbus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=760F307A30689D66',
                  'Streptopelia turtur': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=5788552B694ED7B5',
                  'Streptopelia decaocto': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0C1EFC9B44C459D3',
                  'Syrrhaptes paradoxus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BDCB55F1196CAC6A',
                  'Otis tarda': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C6F33176724AC933',
                  'Chlamydotis macqueenii': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1BCEB0FD7CDFB06A',
                  'Tetrax tetrax': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=56E3016D3370A6D5',
                  'Cuculus canorus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B3D2C3C5B73EC8E8',
                  'Caprimulgus europaeus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=80D4B0FE7FF1D735',
                  'Apus melba': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FA1CAD2906F7C845',
                  'Apus apus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=4E6EF3F983079D73',
                  'Rallus aquaticus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=DE1D2DF4456931FF',
                  'Crex crex': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=7E2572426E200D08',
                  'Porzana porzana': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=460708F99737A6A2',
                  'Gallinula chloropus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=8F82FF8C30667D90',
                  'Fulica atra': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B682B2A9C922D4C4',
                  'Porphyrio porphyrio': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B6838E0C27EAD078',
                  'Porphyrio madagascariensis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=865C039E4B8BE80A',
                  'Zapornia parva': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9106EBE6C0914933',
                  'Zapornia pusilla': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=34D5B04DE53894FF',
                  'Anthropoides virgo': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=64DDD14DF2EB9B39',
                  'Grus grus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=99B8841E764117B1',
                  'Burhinus oedicnemus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C7DB323E37CEDBE6',
                  'Himantopus himantopus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3CAEB7CEEC7FFF50',
                  'Recurvirostra avosetta': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C73ED2F5D88625BA',
                  'Haematopus ostralegus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=ED66316522B99A30',
                  'Pluvialis squatarola': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=27903EF7E618A6A2',
                  'Pluvialis apricaria': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=25A20BA6F7EA9D9A',
                  'Pluvialis dominica': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=2143A8526CA7C809',
                  'Pluvialis fulva': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=07C11CF340D2017A',
                  'Vanellus vanellus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F029489ABD9D1334',
                  'Vanellus spinosus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F5E92B225F648330',
                  'Vanellus gregarius': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D348C2D65FA2DF83',
                  'Vanellus leucurus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A480FDDF8BBC5443',
                  'Charadrius alexandrinus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=AA4385A283B9A81E',
                  'Charadrius hiaticula': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=EDA37B7C5D4A25ED',
                  'Charadrius dubius': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=35EC3BBF166AB032',
                  'Charadrius morinellus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=20BE9DF14579BD4A',
                  'Numenius phaeopus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F9305BAA638BAEFC',
                  'Numenius tenuirostris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=7A35DE8186E4DF43',
                  'Numenius arquata': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3BB5CBA66CF48884',
                  'Limosa lapponica': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9A684C997C1AF1BA',
                  'Limosa limosa': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=454B5CD5F5285B77',
                  'Arenaria interpres': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=DC3050A9771F2CE9',
                  'Calidris canutus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B5CE8FAD18923A94',
                  'Calidris pugnax': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=2DABF98FBEEAB7BB',
                  'Calidris falcinellus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0A14882F5F9F64E6',
                  'Calidris ferruginea': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=143A681C9BCE9A20',
                  'Calidris temminckii': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=5ACF7FB313BEF9EA',
                  'Calidris ruficollis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BBDF2F1BAC640E4D',
                  'Calidris alba': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=06B9BD243A756B28',
                  'Calidris alpina': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=15369E8EB4CBD064',
                  'Calidris maritima': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0A0B84313ACFFB2F',
                  'Calidris bairdii': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1F1AD154DAE2E070',
                  'Calidris minuta': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9936FF4AFB430504',
                  'Calidris fuscicollis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=153BA3069DFCDDCA',
                  'Calidris subruficollis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3A3C62BC935BDA72',
                  'Calidris melanotos': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=ACC99F35F0E8F7EB',
                  'Lymnocryptes minimus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1A15F0C6B4948C52',
                  'Scolopax rusticola': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BFE14290EA4326FA',
                  'Gallinago media': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BCCD5840C7A6D538',
                  'Gallinago gallinago': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9151E0BA75761647',
                  'Xenus cinereus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6D5992EEE12070E8',
                  'Phalaropus lobatus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E6F3BA54577746FB',
                  'Phalaropus fulicarius': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=18A1938091EEEA73',
                  'Actitis hypoleucos': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=8548B07ECA48773F',
                  'Tringa ochropus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A7B17EFC92B53D29',
                  'Tringa erythropus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0895DD84DB3A45D1',
                  'Tringa melanoleuca': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6EB81C98A8FD9CE6',
                  'Tringa nebularia': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=18B415D28BBF934C',
                  'Tringa flavipes': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=2C7A2673444BECF0',
                  'Tringa stagnatilis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=15CF9352AD0E92DF',
                  'Tringa glareola': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=8E67DC5F68BDF62C',
                  'Tringa totanus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D6BFC73A3E067711',
                  'Cursorius cursor': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=DE0A72A7FA1E6DB7',
                  'Glareola pratincola': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D56ABB4EE468E9EF',
                  'Glareola nordmanni': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E1F6A875C32C042D',
                  'Stercorarius skua': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BB041C6E5DB73FC7',
                  'Stercorarius pomarinus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=7CB8F5B711DE64D0',
                  'Stercorarius parasiticus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=39086887E9EAFEB3',
                  'Stercorarius longicaudus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1D4464402EC9FD21',
                  'Alle alle': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B0932D89F1F74318',
                  'Uria aalge': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=39F29B55EF9A542F',
                  'Alca torda': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=64F4DD81371B269F',
                  'Cepphus grylle': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B5AA5952E13FE5F3',
                  'Rissa tridactyla': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FB4D08F0837D4683',
                  'Xema sabini': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=86182656472B476B',
                  'Chroicocephalus genei': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=27CE7132A1848BCD',
                  'Chroicocephalus philadelphia': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0337440E2A88E638',
                  'Chroicocephalus ridibundus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FB02DD9658CC1EC6',
                  'Hydrocoloeus minutus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F89FD6E3A367C008',
                  'Ichthyaetus melanocephalus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=052BFA8A77EED5AF',
                  'Ichthyaetus ichthyaetus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=EF930CDC7CE618F7',
                  'Ichthyaetus audouinii': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F7B9355E42C3F987',
                  'Larus canus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=00DA9D9151189271',
                  'Larus delawarensis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=23863F65441680FA',
                  'Larus argentatus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=8535345BBCE9771B',
                  'Larus michahellis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E074D7069AE1303C',
                  'Larus cachinnans': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=93CA037F6FFE9FDB',
                  'Larus glaucoides': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FB4FCB27CC5566D1',
                  'Larus fuscus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=2D52E3A509137804',
                  'Larus hyperboreus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A59FA446D6B40057',
                  'Larus marinus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E826E9F3FBAED223',
                  'Sternula albifrons': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=17310BF0FE9BAC8A',
                  'Gelochelidon nilotica': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=441918B5AE353C3B',
                  'Hydroprogne caspia': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BC06BC0D1056BC7B',
                  'Chlidonias niger': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=115AF02DD58018FB',
                  'Chlidonias leucopterus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=43CAAEE3B0D305D9',
                  'Chlidonias hybrida': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=7AB4E42B260B5954',
                  'Sterna hirundo': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=4D2FF6F13790ED7E',
                  'Sterna paradisaea': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BDC5CF80BE6CFC21',
                  'Thalasseus sandvicensis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F7504353640C1055',
                  'Gavia stellata': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6C50988A5445ED76',
                  'Gavia arctica': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=CA5852BE6E617DBD',
                  'Gavia immer': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=7E02237895784E9A',
                  'Gavia adamsii': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=5349255DB4579713',
                  'Hydrobates pelagicus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E1638A370D09095C',
                  'Fulmarus glacialis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=049D9AEA4AFBFDFA',
                  'Calonectris diomedea': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FF3D837AAC50A0C9',
                  'Ciconia nigra': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E2817DAE1B24B31E',
                  'Ciconia ciconia': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=28825494A08AFE5A',
                  'Morus bassanus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=534FB490884C6D33',
                  'Microcarbo pygmaeus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=AFF49475BDB69B4E',
                  'Phalacrocorax carbo': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3DF5C587CE3CF1E1',
                  'Gulosus aristotelis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=CECC7B264A61BD22',
                  'Pelecanus onocrotalus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=8BAFB01E85D7AF4B',
                  'Botaurus stellaris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0F42F11AC607C758',
                  'Ixobrychus minutus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=7AAD57ACA1C4ECA9',
                  'Ardea cinerea': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6429024DBA7AB672',
                  'Ardea purpurea': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3395DCF1CE3A8C91',
                  'Ardea alba': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=49D9148A171E7F2E',
                  'Egretta garzetta': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F2858F9FFB9DFDCF',
                  'Bubulcus ibis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6CCDAC53F56435B4',
                  'Ardeola ralloides': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=CE73EBD7A90E9FCF',
                  'Nycticorax nycticorax': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6BB94D7EA4D041A8',
                  'Plegadis falcinellus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D4540F880A3EC3BB',
                  'Threskiornis aethiopicus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=550DE745B77C8079',
                  'Platalea leucorodia': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A0A584C1E7D786FE',
                  'Pandion haliaetus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1327AC55AA9D579B',
                  'Elanus caeruleus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=97C47F3E1BA4129A',
                  'Gypaetus barbatus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=81DB7410BE70406B',
                  'Neophron percnopterus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6D3480A64B4953CE',
                  'Pernis apivorus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=ED5A7E8F6EDBB78E',
                  'Aegypius monachus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=158BDC90F07DF1D2',
                  'Gyps fulvus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=5D1987CEE4005AA2',
                  'Circaetus gallicus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=8372FFBAA4080FBB',
                  'Clanga pomarina': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C2565B6526591E9A',
                  'Clanga clanga': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BAC4CA22EDCC74E7',
                  'Hieraaetus pennatus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=4B8CC2853542FFED',
                  'Aquila nipalensis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A635F56542EE0C16',
                  'Aquila heliaca': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=469DCF57248A1C69',
                  'Aquila chrysaetos': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=5F8E7CA845BD413F',
                  'Aquila fasciata': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=05F1144132A7E4FF',
                  'Circus aeruginosus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E2A19474E62F83E1',
                  'Circus cyaneus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F558C7F96E40C134',
                  'Circus macrourus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=22647E26E5C80F2E',
                  'Circus pygargus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=63B6412E23CC0D93',
                  'Accipiter brevipes': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=8492E4B70A95DC74',
                  'Accipiter nisus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=DB376A66278ED21E',
                  'Accipiter gentilis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=420850D62E855E4D',
                  'Milvus milvus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=451D6FC8A169D726',
                  'Milvus migrans': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=06D9A2C8D1E3678A',
                  'Haliaeetus albicilla': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=5A3D91D3254A568D',
                  'Buteo lagopus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=90B13ACF984D0DDF',
                  'Buteo buteo': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3C0C325D1141B36B',
                  'Buteo rufinus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=CC65921FEBE1BB96',
                  'Tyto alba': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FEE35F4C60D1BBD3',
                  'Otus scops': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=2C7AA1546D80617E',
                  'Bubo scandiacus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=5B23B360E7DEC4A9',
                  'Bubo bubo': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=5516AEB347441B72',
                  'Surnia ulula': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C2018A5DD8CDB5F5',
                  'Glaucidium passerinum': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=79E2AC7C3122B93F',
                  'Athene noctua': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9A7B268C4EF6F803',
                  'Strix aluco': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=37A121744F77C1DB',
                  'Strix uralensis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=93486A5625828721',
                  'Asio otus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FC4D40D2D5CEA6BE',
                  'Asio flammeus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=8F123A11E5DADFDD',
                  'Aegolius funereus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=8AB4EAF6DBFA02CE',
                  'Upupa epops': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FA2F91259125A6FA',
                  'Alcedo atthis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9505E03D7416B365',
                  'Merops apiaster': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=66AA3934DBAD18BC',
                  'Coracias garrulus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=7451A628C39538C5',
                  'Jynx torquilla': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B2E6AB9FC2608DFA',
                  'Picoides tridactylus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=05B8A4F150564A49',
                  'Dendrocoptes medius': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=504B2FD466B8E1D8',
                  'Dendrocopos leucotos': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=4507ACD713D16392',
                  'Dendrocopos major': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D754DB8552A7AA42',
                  'Dendrocopos syriacus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3F54E5FDCF8CFA47',
                  'Dryobates minor': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=AB2F4BC0659B6630',
                  'Picus canus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BC863B3AC0DB9AAA',
                  'Picus viridis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A01014FF0A909DD8',
                  'Dryocopus martius': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=EDB4BBA6E765E593',
                  'Falco naumanni': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BECA271F14F77BEE',
                  'Falco tinnunculus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=2DAB45B833D396A3',
                  'Falco vespertinus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=997A9437E564FCFE',
                  'Falco eleonorae': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9EA1F12D48EB0120',
                  'Falco columbarius': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F3DA111CC8A6841B',
                  'Falco subbuteo': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E91E287A2946B0C9',
                  'Falco biarmicus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3D3808E38BB61165',
                  'Falco cherrug': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A9F5149411AE52AD',
                  'Falco rusticolus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E19252A76FC7845B',
                  'Falco peregrinus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=47E5840880DC9FA8',
                  'Psittacula krameri': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6B1CFC3CFA400D78',
                  'Oriolus oriolus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=92A772BBB88868CD',
                  'Lanius collurio': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F2CEFD1A4EA5F608',
                  'Lanius excubitor': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=DB2501EEBA3D38AA',
                  'Lanius minor': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=8852337B06E8A14E',
                  'Lanius senator': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=7E70D490A6476D16',
                  'Garrulus glandarius': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D8D10F2C5A9AA49F',
                  'Pica pica': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FBBBA943D3AB65E8',
                  'Nucifraga caryocatactes': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=76C74B102E7F401F',
                  'Pyrrhocorax graculus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=45B512E2ECC3DB1D',
                  'Corvus monedula': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D4C32F8E792B65BA',
                  'Corvus frugilegus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1078FFEA23D9DD25',
                  'Corvus corone': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=26FB62DAE4262583',
                  'Corvus cornix': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F13D8350405F3C10',
                  'Corvus corax': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B9B272F40EE1570F',
                  'Periparus ater': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=166CD4402D4A416B',
                  'Lophophanes cristatus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E553193354C74B21',
                  'Poecile palustris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=523763E55D4A8153',
                  'Poecile montanus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F963401E5AFA01DC',
                  'Cyanistes caeruleus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9BE53D340F9A4305',
                  'Cyanistes cyanus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=184A6A8E71DA133A',
                  'Parus major': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E15BC0CB3DEAA621',
                  'Remiz pendulinus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F81EB04951AA84BB',
                  'Eremophila alpestris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FC0A1D951186B019',
                  'Calandrella brachydactyla': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=4091A51E0603BAF2',
                  'Melanocorypha calandra': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BDC24A8AA8A51BF9',
                  'Lullula arborea': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=742EC2F1CA97F56C',
                  'Alauda arvensis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=ED2AC04E888EF9CF',
                  'Galerida cristata': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=21ADC3ED8E24C1C9',
                  'Panurus biarmicus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=7D59F91D9548DCE7',
                  'Iduna caligata': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1A6C6F1718FEDB5D',
                  'Iduna rama': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A8242804046F8F14',
                  'Iduna pallida': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BAE527A2F70F6241',
                  'Hippolais polyglotta': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=DCDD1BCA24E978F5',
                  'Hippolais icterina': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=869C978C8E5840C8',
                  'Acrocephalus paludicola': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C15141A60961F8BC',
                  'Acrocephalus melanopogon': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E1559C49B1A6C31F',
                  'Acrocephalus schoenobaenus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FED5AED5C59A00B6',
                  'Acrocephalus agricola': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=781FE53F2425B4C1',
                  'Acrocephalus dumetorum': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B22EAFC877C38967',
                  'Acrocephalus palustris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B675E006C3745A12',
                  'Acrocephalus scirpaceus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3F0EE4749050AA59',
                  'Acrocephalus arundinaceus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B283E33243C17D97',
                  'Locustella fluviatilis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=2B020CA0ACF13B19',
                  'Locustella luscinioides': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=2D46BB9888C846D0',
                  'Locustella naevia': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BC0E4C9F87721B1A',
                  'Riparia riparia': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=94A1C447583CB6D2',
                  'Ptyonoprogne rupestris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6F2AF9D09463566F',
                  'Hirundo rustica': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=58C502EA7AF3E023',
                  'Cecropis daurica': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F72A871F987F8499',
                  'Delichon urbicum': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E4BB82F50C488B8B',
                  'Phylloscopus sibilatrix': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=572C4C7FD4322D14',
                  'Phylloscopus bonelli': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C00674ED5FC9DB8A',
                  'Phylloscopus inornatus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0C120038E5CA37D7',
                  'Phylloscopus proregulus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=943E36CADFE7551B',
                  'Phylloscopus schwarzi': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9A536399807238AF',
                  'Phylloscopus fuscatus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=96819591FD94B905',
                  'Phylloscopus trochilus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=88F4B969622B8268',
                  'Phylloscopus collybita': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F9F4B04D08108B41',
                  'Phylloscopus ibericus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=12EE678EE03BDFB2',
                  'Phylloscopus trochiloides': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=23EF1BD9DE02E680',
                  'Cettia cetti': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F3E9CE954FAF5EF5',
                  'Aegithalos caudatus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=547163C22167E31B',
                  'Sylvia atricapilla': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=61F9065BE0965E1A',
                  'Sylvia borin': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A6A4FC63261EA8CD',
                  'Curruca nisoria': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1EA60B94FAFE0C5C',
                  'Curruca curruca': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0DCD05BE8EE35C8D',
                  'Curruca nana': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=58F3D3E544D9755B',
                  'Curruca melanocephala': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B0D094830E71F76A',
                  'Curruca cantillans': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B13D68B156442119',
                  'Curruca communis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=14AFBA82D556918C',
                  'Curruca undata': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=85629EF4042C9DBB',
                  'Regulus regulus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1C51C1095E427BB8',
                  'Regulus ignicapilla': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=85B03849153146D8',
                  'Tichodroma muraria': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=89C425901C5B5343',
                  'Sitta europaea': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3C468678E0958FC6',
                  'Certhia familiaris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=73BE9A87F6A32D6A',
                  'Certhia brachydactyla': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=552E2BA9FE43A2EE',
                  'Troglodytes troglodytes': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=AF700208E4339572',
                  'Cinclus cinclus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FDECE3B9278A17EC',
                  'Sturnus vulgaris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=94A4403295E2D9BE',
                  'Pastor roseus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=24208346AD77666E',
                  'Turdus viscivorus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A95B43F1E9D10296',
                  'Turdus philomelos': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D929EB214A698282',
                  'Turdus iliacus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A8A85BCF1AFB7BBD',
                  'Turdus merula': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=88BB4F2A0C8492A5',
                  'Turdus migratorius': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D77E4B418D581FB2',
                  'Turdus obscurus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6E24CCD187765B9A',
                  'Turdus pilaris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D120D5A070E8123C',
                  'Turdus torquatus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=CE71B4FF837F276A',
                  'Turdus atrogularis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=AECDBFFA55C87E24',
                  'Turdus eunomus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E3B6927817B7ABB4',
                  'Turdus naumanni': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=22761AD4A981E2F6',
                  'Muscicapa striata': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=EE8206E703914D22',
                  'Erithacus rubecula': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C809B2B90399A43D',
                  'Luscinia luscinia': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6EC667529FB53E43',
                  'Luscinia megarhynchos': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=7C7F0DEE5B364038',
                  'Luscinia svecica': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=AFD6FD811AA7D6A7',
                  'Tarsiger cyanurus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9F2611E8CB30A09E',
                  'Ficedula parva': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6A3CA06B2496B003',
                  'Ficedula semitorquata': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=BE56C141DDCFDA2E',
                  'Ficedula hypoleuca': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6E352E1870A195B7',
                  'Ficedula albicollis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0B2F80584ED0F07E',
                  'Phoenicurus phoenicurus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=06DD9D954313582E',
                  'Phoenicurus ochruros': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=612B5C244E272075',
                  'Monticola saxatilis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=736D38E7F9967842',
                  'Monticola solitarius': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=41D76F4B19ACB4BD',
                  'Saxicola rubetra': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A0EDAEA2E89A9A96',
                  'Saxicola rubicola': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0EA8F8B905405FB3',
                  'Oenanthe oenanthe': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=DF526047637004DD',
                  'Oenanthe deserti': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=078BC0ED34F512AE',
                  'Oenanthe hispanica': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=CBB941834F230C88',
                  'Oenanthe melanoleuca': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=DF26171F72EF3655',
                  'Bombycilla garrulus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=AEF821EC4625150E',
                  'Prunella collaris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A783468FC167312E',
                  'Prunella montanella': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D32200407D81F285',
                  'Prunella modularis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=26530C865C4A655C',
                  'Passer domesticus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=240E33900CE34D44',
                  'Passer montanus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C22FBF8D36F91BCA',
                  'Montifringilla nivalis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3E389D037AA10A4C',
                  'Motacilla cinerea': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=AE073221679039C2',
                  'Motacilla flava': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=5983D6776C4C4F85',
                  'Motacilla citreola': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=5B0295C122B63ED3',
                  'Motacilla alba': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=400E032C4624AA36',
                  'Anthus richardi': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=41ECD10E24E8772D',
                  'Anthus campestris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=250CDA5828B68D0A',
                  'Anthus pratensis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=14873249B607CEB1',
                  'Anthus trivialis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=365F5E975B414FE6',
                  'Anthus cervinus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=319D044A667563CD',
                  'Anthus spinoletta': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0A3FA18502F4FC70',
                  'Anthus petrosus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E1CBB1C259093F06',
                  'Fringilla coelebs': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=37F522810CADE42A',
                  'Fringilla montifringilla': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E16B2C0328E05DC5',
                  'Coccothraustes coccothraustes': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=84E1F1149261F19E',
                  'Carpodacus erythrinus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3A713345F43AFFA6',
                  'Pinicola enucleator': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=83AC4DAD94AFC411',
                  'Pyrrhula pyrrhula': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=24764DC7AD26E5F7',
                  'Bucanetes githagineus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=8049F70788740F8F',
                  'Chloris chloris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=65BD2033E2A722C8',
                  'Linaria flavirostris': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6CD4E38EB75CA3A0',
                  'Linaria cannabina': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=32635892A4EB874F',
                  'Acanthis flammea': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=A2BB98A9A61F777B',
                  'Acanthis cabaret': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D41F16148782AF8F',
                  'Acanthis hornemanni': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D23A3F75CCD56E6B',
                  'Loxia pytyopsittacus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=CAAD3E23531C26C5',
                  'Loxia curvirostra': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=135564AAF6B01DA2',
                  'Loxia leucoptera': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=80C297E6B82452E7',
                  'Carduelis carduelis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1B235E0052ACC519',
                  'Carduelis citrinella': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=039E0011AA4F1420',
                  'Serinus serinus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C3227709455B9AFF',
                  'Spinus spinus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9820CECA12EC737D',
                  'Calcarius lapponicus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=3534E4CEBACCB166',
                  'Plectrophenax nivalis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9BEBC02505B416EE',
                  'Emberiza melanocephala': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=E2D2CB88A9D95E42',
                  'Emberiza bruniceps': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=DBF8D184AA08A548',
                  'Emberiza calandra': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9A87EBB0B75C410B',
                  'Emberiza cia': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=4836E64E80D5A372',
                  'Emberiza cirlus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9AAB8C2174EFDF60',
                  'Emberiza citrinella': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=56FB47C05CB7275F',
                  'Emberiza leucocephalos': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=43EF3EA79A531279',
                  'Emberiza hortulana': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=4721056132879EB7',
                  'Emberiza schoeniclus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C0B9787440316E20',
                  'Emberiza aureola': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=7574C0E53A34CCFD',
                  'Emberiza pusilla': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=1866F80E52F4075F',
                  'Emberiza rustica': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=DA9746CEC82D30A3',
                  'Haliaeetus leucocephalus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FED3756C',
                  'Anas carolinensis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=DE24B98D',
                  'Streptopelia orientalis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=6658BAC5',
                  'Anser indicus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=B7159EF0',
                  'Dendrocygna arcuata': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=69D272A6',
                  'Mareca sibilatrix': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=0B8AF41F',
                  'Chenonetta jubata': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=149A8E7E',
                  'Callonetta leucophrys': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=45C1096F',
                  'Coloeus monedula': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D4C32F8E',
                  'Platalea alba': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=F86BB1D3',
                  'Meleagris gallopavo': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=9C5ED06A',
                  'Leptoptilos crumenifer': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=03C0F97C',
                  'Alectoris chukar': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=87CBEBF7',
                  'Haliaeetus pelagicus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=C481FB24',
                  'Anas bahamensis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=D2F97D13',
                  'Tachymarptis melba': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=FA1CAD29',
                  'Cyanopica cyanus': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=659D6E44',
                  'Passer hispaniolensis': 'https://avibase.bsc-eoc.org/species.jsp?avibaseid=5A8E09A1'}

missing_czech_pages: Dict[str, str] = {'buřnák lední': 'Northern fulmar',
                                       'čírka karolinská': 'Green-winged teal',
                                       'husa tundrová': 'Tundra bean goose',
                                       'pěnice vousatá': 'Eastern subalpine warbler',
                                       'racek sabinův': "Sabine's gull",
                                       'vodouš žlutonohý': 'Lesser yellowlegs',
                                       'buřňák šedý/severoatlanský': "Cory's shearwater",
                                       'polák dlouhozobý': 'Canvasback',
                                       'vrabec pokřovní': 'Spanish sparrow',
                                       'husička stěhovavá': 'Wandering whistling duck',
                                       'hvízdák chilský': 'Chiloé wigeon',
                                       'orebice horská/čukar': 'Rock partridge',
                                       'kolpík africký': 'African spoonbill',
                                       'hrdlička východní': 'Oriental turtle dove'}

redirected_names: Dict[str, str] = {'kamenáček pestrý': 'Kameňáček pestrý',
                                    'pěvuška horská': 'Pěvuška sibiřská',
                                    'racek audouinův': 'Racek Audouinův',
                                    'racek bonapartův': 'Racek Bonapartův',
                                    'kachnička mandarínská': 'Kachnička mandarinská',
                                    'kachnička karolinská': 'Kachnička karolínská', }

url_mistranslations: Dict[str, str] = {
    'břehule říční': 'https://upload.wikimedia.org/wikipedia/commons/1/12/But_where_is_Africa%3F_%287776447260%29_%28cropped%29.jpg',
    'volavka rusohlavá': 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Cattle_Egret.jpg'}

errors = []


def download_wiki(keyword: str, version: str) -> Dict:
    """
    Download wikipedia page.
    :param keyword: Wikipedia search term.
    :param version: Wikipedia version: en, cs
    :return:
    """
    url = f'https://{version}.wikipedia.org/w/api.php'
    data = {
        'action': 'query',
        'format': 'json',
        'formatversion': 2,
        'prop': 'pageimages|info',
        "inprop": "url",
        'piprop': 'original',
        'titles': keyword
    }
    response = requests.get(url, data)
    return json.loads(response.text)


def optimize_image(img_path: Path) -> None:
    """
    Optimize image convert, resize and optimize.
    :param img_path: Path to image.
    :return: None
    """
    # Convert.
    if img_path.suffix.lower() == '.png':
        png = Image.open(img_path)
        rgb_img = png.convert('RGB')
        img_path = img_path.rename(img_path.with_suffix('.jpg'))
        rgb_img.save(img_path)
    # Optimize.
    img = Image.open(img_path)
    img.save(img_path, optimize=True, quality=95)
    # Resize.
    img = Image.open(img_path)
    img.thumbnail((500, 500), Image.LANCZOS)
    img.save(img_path, "JPEG")


def print_msg(msg: str) -> None:
    """
    Print message to screen, if it is a warning or an error, save it to log list.
    :param msg: Message to print, strings with [ERR], [WRN] are saved.
    :return: None
    """
    print(msg)
    if '[ERR]' in msg:
        errors.append(msg)
    elif '[WAR]' in msg:
        errors.append(msg)


def run() -> None:
    """
    Download data.
    :return: None
    """
    stop: bool = False
    delay: int = 3
    img_count: int = 0
    working_directory = Path(Path.home() / 'Downloads/birds')
    if working_directory.exists():
        print_msg('Removing existing working directory')
        shutil.rmtree(working_directory)
    print_msg(f'Create destination directory: {working_directory}')
    working_directory.mkdir(exist_ok=True, parents=True)

    with open('Seznam-druhu.txt', 'r') as file:
        os.chdir(working_directory)
        lines = len(file.readlines())
        counter = 1
        file.seek(0)
        for line in file.readlines():
            name, latin = line.split(sep=',')
            if name in redirected_names.keys():
                name = redirected_names[name]
            name: str = name.strip()
            latin: str = latin.strip()
            json_data = download_wiki(name, 'cs')
            if 'missing' in json_data['query']['pages'][0]:
                if json_data['query']['pages'][0]['missing']:
                    english_name = missing_czech_pages[name]
                    print_msg(f'[WAR] Nonexistent CS page: {name}, {latin}, trying English: {english_name}')
                    json_data = download_wiki(english_name, 'en')

            full_wiki_url: str = json_data['query']['pages'][0]['fullurl']
            print_msg(f'Downloading: {counter}/{lines} {name}: {latin}, {full_wiki_url}, sleep {delay}s')
            if len(json_data['query']['pages']) <= 0:
                print_msg(f' [ERR] No image: {name}, {latin}')
            else:
                try:
                    img_url_quoted: str = json_data['query']['pages'][0]['original']['source']
                    img_url = urllib.parse.unquote(img_url_quoted, encoding='utf-8')
                    if name in url_mistranslations:
                        img_url = url_mistranslations[name]
                    img_suffix: str = img_url.split(sep='/')[-1].split('.')[-1].lower()
                    dir_name: str = name.replace(' ', '_').replace('/', '_')
                    img_filename: str = dir_name + '.' + img_suffix
                    species_dir = Path(Path.cwd() / dir_name)
                    species_dir.mkdir(exist_ok=True)
                    os.chdir(Path(Path.cwd() / dir_name))
                    try:
                        if Path(Path().cwd() / Path(img_filename)).exists():
                            Path.unlink(Path(Path().cwd() / Path(img_filename)))
                        wget.download(img_url, out=img_filename, bar=None)
                        img_count = img_count + 1
                    except HTTPError as e:
                        print_msg(f' [ERR] Failed image download: {name}, {latin}. {str(e)}')
                        with open(img_filename, 'wb') as f:
                            f.write(requests.get(img_url_quoted).content)

                    create_yaml_metadata(name, latin, full_wiki_url, img_url, img_filename)
                    optimize_image(Path(Path().cwd() / Path(img_filename)))
                    os.chdir(working_directory)
                except KeyError as _:
                    print_msg(f' [ERR] Nonexistent page: {name}, {latin}')
            counter = counter + 1
            if stop:
                break
            time.sleep(delay)
    print_msg(f'Images downloaded: {img_count}')
    print('\nErrors and warnings:')
    with open(Path(Path().cwd() / Path('errors.txt')), 'w') as err_file:
        for msg in sorted(errors):
            msg: str
            print(msg.strip())
            err_file.write(msg)


def create_yaml_metadata(name: str, latin: str, wiki_url: str, img_url: str, img_file) -> None:
    """
    Data:
    http://www.birdphoto.cz/?lang=cz&sc_lang=cz&action=select&cat_id=1&subcat_id=&author_id=
    https://avibase.bsc-eoc.org/search.jsp?lang=EN&isadv=yes
    bird_yml = {'popis': {'samec': {'fotky': [{'zdroj': 'test test', 'url': 'http://...', 'file': ''},
                                          {'zdroj': 'test test', 'url': 'http://...'}, 'file': ''],
                                'barvy': [{'hlava': ['cerna', 'cervena']},
                                          {'křídla': ['cerna', 'cervena']},
                                          {'hruď': ['cervena']},
                                          {'ocas': ['cerna']},
                                          {'nohy': ['cerna']},
                                          {'záda': ['cerna', 'cervena']},
                                          {'zobák': ['zluta']}],
                                'kropenatost': 'ne'},
                      'samice': []},
            'velikost': 'mini',
            'latinsky': 'lorem ipsum',
            'jméno' : 'alkoun obecný'
            'typ': 'dravec',
            'odkazy': {'wiki': 'http://',
                       'více fotek': 'http://',
                       'celosvětová databáze': 'http://'}}
            'dodatek': 'lorem ipsum'
    :param name: Bird name
    :param latin: latin species name
    :param wiki_url: wikipedia article url
    :param img_url: wiki image url
    :param img_file: image filename
    :return: None
    """
    birdphoto_stub = 'http://www.birdphoto.cz/?lang=cz&sc_lang=cz&action=select&cat_id=1&subcat_id=&author_id=&sort_id='
    additional_photos_url = ''
    avibase_url = ''
    if latin not in avibase_id_map.keys():
        print_msg(f' [ERR] No avibase latin key: {name}, {latin}')
    else:
        avibase_url = avibase_id_map[latin]
    for name_key in birdphoto_id_map.keys():
        if name.lower() in str(name_key).lower():
            # Sometimes the key includes two alternate names.
            additional_photos_url = f'{birdphoto_stub}{birdphoto_id_map[name_key]}'
    if not additional_photos_url:
        print_msg(f' [WAR] No additional photos on birdphoto: {name}, {latin}')
    bird_yml = {'popis': {'samec': {'fotky': [{'zdroj': 'wikipedia', 'url': img_url, 'file': img_file}],
                                    'barvy': [{'hlava': []},
                                              {'křídla': []},
                                              {'hruď': []},
                                              {'ocas': []},
                                              {'nohy': []},
                                              {'záda': []},
                                              {'zobák': []}],
                                    'kropenatost': ''},
                          'samice': []},
                'velikost': '',
                'latinsky': latin,
                'jméno': name.lower().capitalize(),
                'typ': '',
                'dodatek': '',
                'odkazy': {'wiki': wiki_url,
                           'více fotek': additional_photos_url,
                           'celosvětová databáze': avibase_url}}
    metadata_path = Path(Path.cwd() / 'data.yml')
    with open(metadata_path, 'w', encoding='utf-8') as file:
        yaml.dump(bird_yml, file, allow_unicode=True)


if __name__ == '__main__':
    try:
        run()
    except KeyboardInterrupt as _:
        print("Stopped")
